"use client";

import '@component/styles/globals.css'

import {PersonProvider} from "@component/context/PersonContext";
import {ThemeProvider} from "@component/context/ThemeContext";
import { SessionProvider } from 'next-auth/react'
import NavBar from "@component/components/NavBar";
import { usePathname  } from "next/navigation";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const pathname = usePathname ();

    return (
    <SessionProvider>
      <html lang="en">
        <body>
            <ThemeProvider>
              <PersonProvider>
                  {pathname !== '/' && <NavBar />}
                  {children}
              </PersonProvider>
            </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  )
}
