import '@component/styles/globals.css'

import {PersonProvider} from "@component/context/PersonContext";
import {ThemeProvider} from "@component/context/ThemeContext";
import {UserProvider} from "@auth0/nextjs-auth0/client";
import NavBar from "@component/components/NavBar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <ThemeProvider>
            <PersonProvider>
              <NavBar />
              {children}
            </PersonProvider>
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  )
}
